/// App-chrome strings (corpus text is localized in the data files).
/// Adding a language = adding entries here, never a schema change.
class S {
  final String lang;
  const S(this.lang);

  static const _en = <String, String>{
    'appName': 'morphcook',
    'tagline': 'the same dish exists for every body',
    'navHome': 'home',
    'navSearch': 'search',
    'navCookbook': 'cookbook',
    'navPlan': 'plan',
    'navSettings': 'settings',
    'featuredToday': 'featured today',
    'fromTheKitchen': 'from the kitchen',
    'allCategories': 'everything',
    'categoryEmpty': 'nothing in this section fits your profile yet.',
    'editionFor': 'edition for',
    'yourCookbook': 'your cookbook',
    'cookbookEmpty': 'nothing saved yet.\nfind a dish & make it yours.',
    'cookbookHint': 'save a version you love, or write down one of your own.',
    'saved': 'saved',
    'save': 'save',
    'myRecipes': 'my recipes',
    'privateRecipe': 'private',
    'addRecipe': 'add your own recipe',
    'newRecipe': 'new recipe',
    'editRecipe': 'edit recipe',
    'deleteRecipe': 'delete recipe',
    'deleteRecipeConfirm':
        'delete this recipe, its cookbook copy, plans and history?',
    'privateRecipeHint':
        'kept only on this device. it is included when you export a backup.',
    'recipeTitle': 'recipe title',
    'recipeDescription': 'notes or story (optional)',
    'recipeTime': 'total minutes',
    'addIngredient': 'add ingredient',
    'ingredientName': 'ingredient',
    'quantity': 'quantity',
    'unit': 'unit',
    'ingredientNote': 'note (optional)',
    'removeIngredient': 'remove ingredient',
    'addStep': 'add step',
    'stepInstructions': 'instructions',
    'timerMinutesOptional': 'timer minutes (optional)',
    'removeStep': 'remove step',
    'saveChanges': 'save changes',
    'createRecipe': 'create recipe',
    'recipeValidation':
        'add a title, valid time and servings, and complete every ingredient and step.',
    'personalRecipeLimit':
        'this cookbook already has the maximum of 500 personal recipes.',
    'personalRecipeBackupLimit':
        'these recipes contain too much text for a safe backup. shorten a recipe before saving another.',
    'personalRecipeSaveFailed':
        'this recipe could not be saved. check available storage and try again.',
    'personalRecipeDeleteFailed':
        'this recipe could not be deleted. check available storage and try again.',
    'personalRecipesEmpty':
        'your own recipes will live here — private, unless you share a backup.',
    'chooseRecipeImage': 'add your photo',
    'changeRecipeImage': 'change photo',
    'removeRecipeImage': 'remove photo',
    'recipeImageTooLarge': 'that image is larger than 8 MB.',
    'recipeImageDimensionsTooLarge':
        'that image has too many pixels to use safely.',
    'recipeImageUnsupported': 'choose a JPEG, PNG or WebP image.',
    'recipeImageReadError': 'that image could not be read.',
    'recipeImageStorageFull':
        'photo storage is full. remove another recipe photo first.',
    'recipeImageRemoveFailed':
        'that photo could not be removed. check available storage and try again.',
    'confirmBackupPassword': 'confirm backup password',
    'confirmBackupPasswordHint':
        'enter it again — lost backup passwords cannot be recovered.',
    'backupPasswordsDiffer': 'the two backup passwords do not match.',
    'backupExportFailed': 'the backup could not be exported.',
    'backupImportFailed': 'the backup could not be restored safely.',
    'searchHint': 'search dishes, ingredients, moods…',
    'searchEmpty': 'no recipes found for',
    'searchEmptyNote':
        'we wrote it down — your wish helps us decide what to cook up next.',
    'filters': 'filters',
    'diet': 'diet',
    'effort': 'effort',
    'calorieLevel': 'calorie level',
    'time': 'time',
    'ingredients': 'ingredients',
    'method': 'method',
    'macros': 'macros',
    'perServing': 'per serving',
    'servings': 'servings',
    'minutes': 'min',
    'calories': 'kcal',
    'protein': 'protein',
    'carbs': 'carbs',
    'fat': 'fat',
    'noVariantNote': 'no version yet for',
    'comboUnavailable': 'not written yet — maybe soon',
    'outsideProfile':
        'this version sits outside your profile — yours to cook anyway',
    'outsideProfileCount': 'versions outside your profile',
    'outsideCalories': 'outside your calorie target',
    'showAnyway': 'show versions outside my target',
    'startCooking': 'start cooking',
    'resumeCooking': 'resume cooking',
    'step': 'step',
    'of': 'of',
    'startTimer': 'start timer',
    'pause': 'pause',
    'resume': 'resume',
    'timerDone': 'time! next move.',
    'done': 'done',
    'finishCooking': 'finish',
    'cookedIt': 'that\'s dinner. well done.',
    'cookAgainNote': 'logged to your history.',
    'backToRecipe': 'back to the recipe',
    'quickTapHint': 'tap anywhere on the step to go forward',
    'addToList': 'add to shopping list',
    'addedToList': 'added to your shopping list',
    'shoppingList': 'shopping list',
    'shoppingEmpty': 'list is empty.\nadd a recipe or plan your week.',
    'clearChecked': 'clear checked',
    'clearAll': 'clear all',
    'mealPlan': 'meal plan',
    'week': 'week',
    'breakfast': 'breakfast',
    'lunch': 'lunch',
    'dinner': 'dinner',
    'mon': 'mon',
    'tue': 'tue',
    'wed': 'wed',
    'thu': 'thu',
    'fri': 'fri',
    'sat': 'sat',
    'sun': 'sun',
    'planEmptySlot': 'tap to plan',
    'exportWeekToList': 'send week to shopping list',
    'weekExported': 'week sent to your shopping list',
    'pickRecipe': 'pick a recipe',
    'fromCookbook': 'from your cookbook',
    'fromSearch': 'from search',
    'removeFromSlot': 'remove',
    'settings': 'settings',
    'profile': 'profile',
    'yourName': 'your name',
    'language': 'language',
    'dietAllergies': 'diet & avoidances',
    'avoidClasses': 'avoid whole groups',
    'avoidSpecific': 'avoid specific ingredients',
    'avoidSpecificHint': 'type an ingredient — apples, cilantro…',
    'requiredAttributes': 'must-haves',
    'calorieTarget': 'calorie target per meal',
    'timeBudget': 'time budget',
    'noLimit': 'no limit',
    'preferredEffort': 'usual effort mood',
    'showVariantTags': 'show variant tags on cards',
    'adaptationPrefs': 'adaptation preferences',
    'accessibility': 'accessibility',
    'theme': 'appearance',
    'themeLight': 'light',
    'themeDark': 'dark',
    'readableText': 'easy-reading text',
    'readableTextHint':
        'clear letterforms, no italics or handwriting, calm covers instead of stripes — easier with dyslexia or low vision.',
    'reduceMotion': 'reduce motion',
    'systemDefault': 'system default',
    'on': 'on',
    'off': 'off',
    'visualAlert': 'visual timer alert (flash)',
    'visualAlertHint':
        'flashes the screen when a timer ends — for when sound isn\'t an option.',
    'quickTap': 'one-handed cook mode (tap to advance)',
    'quickTapSettingHint':
        'a single tap on the step content goes to the next step.',
    'halalKosherNote':
        'we say "halal-compatible" / "kosher-compatible ingredients" only. certification belongs to sourcing — slaughter, supervision — not to a recipe text.',
    'backup': 'backup & restore',
    'exportBackup': 'export backup',
    'importBackup': 'import backup',
    'backupPassword': 'backup password (optional)',
    'backupPasswordHint':
        'encrypts the complete backup with AES-256-GCM. with a password, no plain copy is shared. a forgotten password cannot be recovered.',
    'enterPassword': 'enter password',
    'importMerge': 'merge with my data',
    'importReplace': 'replace my data',
    'importDone': 'backup restored.',
    'shoppingInsights': 'shopping insights',
    'varietyScore': 'variety score',
    'uniqueIngredients': 'unique ingredients',
    'topIngredients': 'most added',
    'seasonal': 'by month',
    'insightsEmpty':
        'no shopping history yet — add recipes to your list and this page starts telling stories.',
    'helpCenter': 'help center',
    'faqSearchHint': 'search the help center…',
    'all': 'all',
    'learnMore': 'learn more',
    'kitchenReference': 'kitchen reference',
    'whereToFind': 'where to find it',
    'storage': 'storage',
    'tips': 'tips',
    'aboutSupport': 'about & support',
    'supportMadeBy': 'made by the morpheus',
    'supportBody':
        'yes — an ai wrote this app. the prompts, the reviews and the token bill were still me. if you want it to stay ad-free and open, with new recipes coming, you can support me here.',
    'supportPatreon': 'support on patreon',
    'supportWebsite': 'the-morpheus.de',
    'resetApp': 'start over (erase everything)',
    'resetConfirm':
        'erase profile, cookbook, personal recipes, photos, plans and history? bundled recipes stay.',
    'cancel': 'cancel',
    'erase': 'erase',
    'history': 'history',
    'historyEmpty': 'nothing cooked yet.',
    'obLanguageTitle': 'which language feels like home?',
    'obNameTitle': 'what should we call you?',
    'obNameHint': 'first name, nickname, anything',
    'obDietTitle': 'how do you eat?',
    'obDietSub':
        'this never filters you out of a dish — it picks the version that\'s yours.',
    'obAllergyTitle': 'anything to keep out of the kitchen?',
    'obPersonalize': 'set diet & allergies first',
    'obSetupLater':
        'optional — diet, allergies, time and calorie preferences stay editable in settings.',
    'obSaveFailed':
        'your setup could not be saved. check available storage and try again.',
    'obTargetsTitle': 'targets, gently',
    'obCalories': 'calories per meal',
    'obTime': 'minutes you usually have',
    'obConfirmTitle': 'your cookbook is ready',
    'obConfirmBody':
        'every dish in here exists in a version written for you. not adapted. written.',
    'next': 'next',
    'back': 'back',
    'letsCook': 'open my cookbook',
    'skip': 'skip',
    'whyHidden': 'why is a recipe hidden?',
    'variantFor': 'as it exists for you',
    'otherVersions': 'every body\'s version',
    'cookMode': 'cook mode',
    'overTime': 'over your time budget',
    'avoidedHit': 'contains something you avoid',
    'missingMust': 'missing one of your must-haves',
  };

  static const _de = <String, String>{
    'appName': 'morphcook',
    'tagline': 'dasselbe Gericht gibt es für jeden Körper',
    'navHome': 'Start',
    'navSearch': 'Suche',
    'navCookbook': 'Kochbuch',
    'navPlan': 'Plan',
    'navSettings': 'Mehr',
    'featuredToday': 'heute im Blatt',
    'fromTheKitchen': 'aus der Küche',
    'allCategories': 'alles',
    'categoryEmpty': 'in dieser Rubrik passt noch nichts zu deinem Profil.',
    'editionFor': 'Ausgabe für',
    'yourCookbook': 'dein Kochbuch',
    'cookbookEmpty':
        'noch nichts gespeichert.\nfinde ein Gericht & mach es zu deinem.',
    'cookbookHint':
        'speichere deine Lieblingsversion oder schreib dein eigenes Rezept auf.',
    'saved': 'gespeichert',
    'save': 'speichern',
    'myRecipes': 'meine Rezepte',
    'privateRecipe': 'privat',
    'addRecipe': 'eigenes Rezept hinzufügen',
    'newRecipe': 'neues Rezept',
    'editRecipe': 'Rezept bearbeiten',
    'deleteRecipe': 'Rezept löschen',
    'deleteRecipeConfirm':
        'dieses Rezept samt Kochbuch-Eintrag, Plänen und Historie löschen?',
    'privateRecipeHint':
        'bleibt nur auf diesem Gerät. beim Backup-Export wird es mitgesichert.',
    'recipeTitle': 'Rezeptname',
    'recipeDescription': 'Notizen oder Geschichte (optional)',
    'recipeTime': 'Minuten insgesamt',
    'addIngredient': 'Zutat hinzufügen',
    'ingredientName': 'Zutat',
    'quantity': 'Menge',
    'unit': 'Einheit',
    'ingredientNote': 'Notiz (optional)',
    'removeIngredient': 'Zutat entfernen',
    'addStep': 'Schritt hinzufügen',
    'stepInstructions': 'Anleitung',
    'timerMinutesOptional': 'Timer-Minuten (optional)',
    'removeStep': 'Schritt entfernen',
    'saveChanges': 'Änderungen speichern',
    'createRecipe': 'Rezept anlegen',
    'recipeValidation':
        'ergänze Name, gültige Zeit und Portionen sowie jede Zutat und jeden Schritt.',
    'personalRecipeLimit':
        'dieses Kochbuch enthält bereits maximal 500 eigene Rezepte.',
    'personalRecipeBackupLimit':
        'diese Rezepte enthalten zu viel Text für ein sicheres Backup. kürze ein Rezept, bevor du ein weiteres speicherst.',
    'personalRecipeSaveFailed':
        'dieses Rezept konnte nicht gespeichert werden. prüfe den freien Speicher und versuche es erneut.',
    'personalRecipeDeleteFailed':
        'dieses Rezept konnte nicht gelöscht werden. prüfe den freien Speicher und versuche es erneut.',
    'personalRecipesEmpty':
        'hier wohnen deine eigenen Rezepte — privat, außer du teilst ein Backup.',
    'chooseRecipeImage': 'eigenes Foto hinzufügen',
    'changeRecipeImage': 'Foto ändern',
    'removeRecipeImage': 'Foto entfernen',
    'recipeImageTooLarge': 'dieses Bild ist größer als 8 MB.',
    'recipeImageDimensionsTooLarge':
        'dieses Bild hat zu viele Pixel, um es sicher zu verwenden.',
    'recipeImageUnsupported': 'wähle ein JPEG-, PNG- oder WebP-Bild.',
    'recipeImageReadError': 'dieses Bild konnte nicht gelesen werden.',
    'recipeImageStorageFull':
        'der Fotospeicher ist voll. entferne zuerst ein anderes Rezeptfoto.',
    'recipeImageRemoveFailed':
        'dieses Foto konnte nicht entfernt werden. prüfe den freien Speicher und versuche es erneut.',
    'confirmBackupPassword': 'Backup-Passwort bestätigen',
    'confirmBackupPasswordHint':
        'gib es erneut ein — verlorene Backup-Passwörter können nicht wiederhergestellt werden.',
    'backupPasswordsDiffer':
        'die beiden Backup-Passwörter stimmen nicht überein.',
    'backupExportFailed': 'das Backup konnte nicht exportiert werden.',
    'backupImportFailed':
        'das Backup konnte nicht sicher wiederhergestellt werden.',
    'searchHint': 'Gerichte, Zutaten, Stimmungen…',
    'searchEmpty': 'keine Rezepte gefunden für',
    'searchEmptyNote':
        'wir haben es notiert — dein Wunsch hilft uns beim nächsten Kochbuch-Update.',
    'filters': 'Filter',
    'diet': 'Ernährung',
    'effort': 'Aufwand',
    'calorieLevel': 'Kalorien-Level',
    'time': 'Zeit',
    'ingredients': 'Zutaten',
    'method': 'Zubereitung',
    'macros': 'Nährwerte',
    'perServing': 'pro Portion',
    'servings': 'Portionen',
    'minutes': 'Min.',
    'calories': 'kcal',
    'protein': 'Eiweiß',
    'carbs': 'Kohlenhydrate',
    'fat': 'Fett',
    'noVariantNote': 'noch keine Version für',
    'comboUnavailable': 'noch nicht geschrieben — vielleicht bald',
    'outsideProfile':
        'diese Version liegt außerhalb deines Profils — koch sie trotzdem',
    'outsideProfileCount': 'Versionen außerhalb deines Profils',
    'outsideCalories': 'außerhalb deines Kalorienziels',
    'showAnyway': 'Versionen außerhalb meines Ziels zeigen',
    'startCooking': 'loskochen',
    'resumeCooking': 'weiterkochen',
    'step': 'Schritt',
    'of': 'von',
    'startTimer': 'Timer starten',
    'pause': 'Pause',
    'resume': 'weiter',
    'timerDone': 'Zeit! nächster Zug.',
    'done': 'fertig',
    'finishCooking': 'fertig',
    'cookedIt': 'das war\'s. gut gemacht.',
    'cookAgainNote': 'in deiner Historie vermerkt.',
    'backToRecipe': 'zurück zum Rezept',
    'quickTapHint': 'tippe irgendwo auf den Schritt, um weiterzugehen',
    'addToList': 'auf die Einkaufsliste',
    'addedToList': 'zur Einkaufsliste hinzugefügt',
    'shoppingList': 'Einkaufsliste',
    'shoppingEmpty':
        'Liste ist leer.\nfüg ein Rezept hinzu oder plane deine Woche.',
    'clearChecked': 'Erledigtes löschen',
    'clearAll': 'alles löschen',
    'mealPlan': 'Wochenplan',
    'week': 'Woche',
    'breakfast': 'Frühstück',
    'lunch': 'Mittag',
    'dinner': 'Abend',
    'mon': 'Mo',
    'tue': 'Di',
    'wed': 'Mi',
    'thu': 'Do',
    'fri': 'Fr',
    'sat': 'Sa',
    'sun': 'So',
    'planEmptySlot': 'antippen & planen',
    'exportWeekToList': 'Woche auf die Einkaufsliste',
    'weekExported': 'Woche auf deine Einkaufsliste gelegt',
    'pickRecipe': 'Rezept auswählen',
    'fromCookbook': 'aus deinem Kochbuch',
    'fromSearch': 'aus der Suche',
    'removeFromSlot': 'entfernen',
    'settings': 'Einstellungen',
    'profile': 'Profil',
    'yourName': 'dein Name',
    'language': 'Sprache',
    'dietAllergies': 'Ernährung & Ausschlüsse',
    'avoidClasses': 'ganze Gruppen meiden',
    'avoidSpecific': 'einzelne Zutaten meiden',
    'avoidSpecificHint': 'Zutat eintippen — Äpfel, Koriander…',
    'requiredAttributes': 'Must-haves',
    'calorieTarget': 'Kalorienziel pro Mahlzeit',
    'timeBudget': 'Zeitbudget',
    'noLimit': 'kein Limit',
    'preferredEffort': 'übliche Aufwands-Stimmung',
    'showVariantTags': 'Varianten-Tags auf Karten zeigen',
    'adaptationPrefs': 'Anpassungs-Einstellungen',
    'accessibility': 'Barrierefreiheit',
    'theme': 'Erscheinungsbild',
    'themeLight': 'Hell',
    'themeDark': 'Dunkel',
    'readableText': 'gut lesbare Schrift',
    'readableTextHint':
        'klare Buchstaben ohne Schnörkel, keine Kursive oder Handschrift, ruhige Flächen statt Streifen — hilfreich bei LRS oder Sehbehinderung.',
    'reduceMotion': 'Bewegung reduzieren',
    'systemDefault': 'Systemstandard',
    'on': 'an',
    'off': 'aus',
    'visualAlert': 'visueller Timer-Alarm (Blitz)',
    'visualAlertHint':
        'der Bildschirm blitzt auf, wenn ein Timer endet — falls Ton keine Option ist.',
    'quickTap': 'Einhand-Kochmodus (Tippen = weiter)',
    'quickTapSettingHint': 'ein Tipp auf den Schritt springt zum nächsten.',
    'halalKosherNote':
        'wir sagen nur „halal-kompatible" / „koscher-kompatible Zutaten". Zertifizierung gehört zur Beschaffung — Schlachtung, Aufsicht — nicht zu einem Rezepttext.',
    'backup': 'Backup & Wiederherstellen',
    'exportBackup': 'Backup exportieren',
    'importBackup': 'Backup importieren',
    'backupPassword': 'Backup-Passwort (optional)',
    'backupPasswordHint':
        'verschlüsselt das komplette Backup mit AES-256-GCM. mit Passwort wird keine offene Kopie geteilt. ein vergessenes Passwort ist nicht wiederherstellbar.',
    'enterPassword': 'Passwort eingeben',
    'importMerge': 'mit meinen Daten zusammenführen',
    'importReplace': 'meine Daten ersetzen',
    'importDone': 'Backup wiederhergestellt.',
    'shoppingInsights': 'Einkaufs-Einblicke',
    'varietyScore': 'Vielfalts-Score',
    'uniqueIngredients': 'verschiedene Zutaten',
    'topIngredients': 'am häufigsten dabei',
    'seasonal': 'nach Monat',
    'insightsEmpty':
        'noch keine Einkaufshistorie — leg Rezepte auf die Liste und diese Seite fängt an zu erzählen.',
    'helpCenter': 'Hilfe-Center',
    'faqSearchHint': 'im Hilfe-Center suchen…',
    'all': 'alle',
    'learnMore': 'mehr erfahren',
    'kitchenReference': 'Küchen-Lexikon',
    'whereToFind': 'wo du es findest',
    'storage': 'Lagerung',
    'tips': 'Tipps',
    'aboutSupport': 'Über & Unterstützen',
    'supportMadeBy': 'gemacht von The Morpheus',
    'supportBody':
        'ja — diese App hat eine KI geschrieben. Prompts, Reviews und die Token-Rechnung waren trotzdem ich. Wenn sie werbefrei und offen bleiben soll, mit immer neuen Rezepten, kannst du mich hier unterstützen.',
    'supportPatreon': 'auf Patreon unterstützen',
    'supportWebsite': 'the-morpheus.de',
    'resetApp': 'neu anfangen (alles löschen)',
    'resetConfirm':
        'Profil, Kochbuch, eigene Rezepte, Fotos, Pläne und Historie löschen? App-Rezepte bleiben.',
    'cancel': 'abbrechen',
    'erase': 'löschen',
    'history': 'Historie',
    'historyEmpty': 'noch nichts gekocht.',
    'obLanguageTitle': 'welche Sprache fühlt sich nach Zuhause an?',
    'obNameTitle': 'wie sollen wir dich nennen?',
    'obNameHint': 'Vorname, Spitzname, egal',
    'obDietTitle': 'wie isst du?',
    'obDietSub':
        'das filtert dich nie aus einem Gericht heraus — es wählt die Version, die deine ist.',
    'obAllergyTitle': 'soll etwas aus der Küche bleiben?',
    'obPersonalize': 'Ernährung & Allergien zuerst einstellen',
    'obSetupLater':
        'optional — Ernährung, Allergien, Zeit- und Kalorienziele bleiben jederzeit in den Einstellungen änderbar.',
    'obSaveFailed':
        'deine Einstellungen konnten nicht gespeichert werden. Prüfe den freien Speicher und versuche es erneut.',
    'obTargetsTitle': 'Ziele, ganz entspannt',
    'obCalories': 'Kalorien pro Mahlzeit',
    'obTime': 'Minuten, die du meistens hast',
    'obConfirmTitle': 'dein Kochbuch ist bereit',
    'obConfirmBody':
        'jedes Gericht hier gibt es in einer Version, die für dich geschrieben wurde. nicht angepasst. geschrieben.',
    'next': 'weiter',
    'back': 'zurück',
    'letsCook': 'mein Kochbuch öffnen',
    'skip': 'überspringen',
    'whyHidden': 'warum ist ein Rezept versteckt?',
    'variantFor': 'so, wie es für dich existiert',
    'otherVersions': 'die Versionen aller Körper',
    'cookMode': 'Kochmodus',
    'overTime': 'über deinem Zeitbudget',
    'avoidedHit': 'enthält etwas, das du meidest',
    'missingMust': 'eins deiner Must-haves fehlt',
  };

  String call(String key) =>
      (lang == 'de' ? _de[key] : _en[key]) ?? _en[key] ?? key;
}
